language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
  - name: test
  - name: deploy
    if: tag IS present  # Only run deploy stage if a tag is present 

jobs:
  include:
    - stage: build
      script:
        - chmod +x ./gradlew  # Add permission to execute gradlew
        - ./gradlew clean compileJava

    - stage: test
      script:
        - chmod +x ./gradlew  # Add permission to execute gradlew
        - ./gradlew test
      after_failure:
        - echo "Tests failed. Check the test results for details."
      after_success:
        - echo "Tests passed successfully."
    
    - stage: deploy
      script:
        - chmod +x ./gradlew  # Add permission to execute gradlew
        - ./gradlew build  # Build the project
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file:
          - build/libs/*  # JAR file
          - build/reports/tests/*           # Test Report (HTML) ...
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    recipients:
      - nawafshrifan@gmail.com
    on_success: always
    on_failure: always
