language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
  - name: test
  - name: Deployement
  - name: deploy
    if: tag IS present  # Only run deploy stage if a tag is present 

jobs:
  include:
    - stage: build
      before_script:
        - chmod +x ./gradlew  # Ensure gradlew is executable
      script:
        - ./gradlew clean compileJava

    - stage: test
      before_script:
        - chmod +x ./gradlew  # Ensure gradlew is executable
      script:
        - ./gradlew test
      after_failure:
        - echo "Tests failed. Check the test results for details."
      after_success:
        - echo "Tests passed successfully."
    
    - stage: Deployement
      script:
        - java -jar ./build/libs/hello-world-java-V1.jar

    - stage: deploy
      before_script:
        - chmod +x ./gradlew  # Ensure gradlew is executable
      script:
        - ./gradlew build  # Build the project
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file:
          - build/libs/*  # JAR file
          - build/reports/tests/*  # Test Report (HTML)
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    recipients:
      - nawafshrifan@gmail.com
    on_success: always
    on_failure: always
